### ISSUE TITLE
you want an index.yml, but you don't tell the user how to get it

### ISSUE THREAD

**Issue by SvenDowideit** [joshwget/strato#2]
```
$ docker run -it --rm joshwget/strato:0.0.2 sh
/ # strato add bash
panic: open /packages/index.yml: no such file or directory

goroutine 1 [running]:
panic(0x6eda60, 0xc42000d3b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /go/src/github.com/joshwget/strato/main.go:43 +0x3f0
```

**Comment by joshwget** [comment]
strato reads from `/etc/strato/repositories` to determine where to find packages. It's not set by default right now. `strato --source="https://github.com/joshwget/strato-packages/raw/master/0.0.2/$(get-arch)/" add <packages>` can be used until it is.
